name: docker

on: [push, pull_request]

jobs:
  compile:
    runs-on: ubuntu-20.04
    container: mirisbowring/texlive_ctan_basic:2019

    steps:
    - name: Check out source
      uses: actions/checkout@v2

    - name: Compile
      working-directory: demo
      run: latex main.tex

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: document
        path: demo/main.dvi
