name: docker

on: [push, pull_request]

jobs:
  compile:
    strategy:
      matrix:
        container:
        - mirisbowring/texlive_ctan_basic:2019
        - mirisbowring/texlive_ctan_full:2019

    runs-on: ubuntu-20.04
    container: ${{ matrix.container }}
    name: docker ${{ matrix.container }}

    steps:
    - name: Check out source
      uses: actions/checkout@v2

    - name: Compile
      working-directory: demo
      run: latex main.tex

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: document
        path: demo/main.dvi
